CREATE TABLE CATEGORY (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT
);

CREATE TABLE COURSE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    CATEGORY_ID INTEGER,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);