POST http://localhost:8080/products
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Description 1",
    "price": 100.00
}

###

GET http://localhost:8080/products?page=1&limit=10&sort=asc

###

GET http://localhost:8080/products/32d5da52-473e-4c68-b195-b2f84198b76f

###

PUT http://localhost:8080/products/32d5da52-473e-4c68-b195-b2f84198b76f
Content-Type: application/json

{
    "name": "Updated Product",
    "description": "Updated Description",
    "price": 150.00
}

###

DELETE http://localhost:8080/products/92beeafc-e552-47ee-8d55-266d05a0e281