services:
  mysql:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_USER: felipe
      MYSQL_PASSWORD: admin123
    ports:
      - "3308:3306"
    volumes:
      - mysql-db-data-pos-goexpert:/var/lib/mysql

volumes:
  mysql-db-data-pos-goexpert:
