// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Category struct {
	ID          int32
	Name        string
	Description sql.NullString
}

type Course struct {
	ID          int32
	Name        string
	Description sql.NullString
	CategoryID  sql.NullInt32
}
